# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32cc68b66a595f4eb6a9a0cc84a5accdcc7642ce7629b2305442ff859f6e2a0628fee1fb744565adf23878cf3d22884da72b522ba573a7faca376d2a2cf948bb

test:
  secret_key_base: 611f3516007592eea69cb1caf45d0d568b9213c63488c1b1488a1da52bb6de54ffa2505567c0d5094a8abc9824b9394e5bfeb39c01798ce6f019bc9721026191

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
